'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const errors=[],requests=[],url=pathToFileURL(path.resolve('build/game.html')).href;fs.mkdirSync('verification',{recursive:true});
 function watch(page){page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});}
 async function full(page){const v=page.viewportSize(),r=await page.locator('#c').boundingBox();assert.ok(Math.abs(r.width-v.width)<2&&Math.abs(r.height-v.height)<2&&r.x===0&&r.y===0,JSON.stringify({v,r}));for(const id of ['bL','bR','bJ','bDash']){const b=await page.locator('#'+id).boundingBox();assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=v.width+1&&b.y+b.height<=v.height+1&&b.width>=56&&b.height>=56,id+JSON.stringify(b));}}
 try{
  const page=await browser.newPage({viewport:{width:1280,height:800}});watch(page);await page.goto(url);await page.getByRole('button',{name:'▶ BOSHLASH',exact:true}).waitFor();await page.screenshot({path:'verification/desktop-menu.png'});await full(page);
  await page.getByRole('button',{name:'▶ BOSHLASH',exact:true}).click();await page.waitForFunction(()=>game.state==='playing'&&Sound.context?.state==='running');
  const before=await page.evaluate(()=>game.player.x);await page.keyboard.down('ArrowRight');await page.waitForTimeout(150);await page.keyboard.press('Space');await page.keyboard.up('ArrowRight');await page.waitForFunction(()=>game.player.y<-40);assert.ok(await page.evaluate(x=>game.player.x>x,before));
  await page.locator('#pauseBtn').click();assert.equal(await page.evaluate(()=>game.state),'paused');const timer=await page.evaluate(()=>game.timer);await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>game.timer),timer);await page.getByRole('button',{name:'▶ DAVOM ETISH',exact:true}).click();await page.waitForFunction(()=>game.state==='playing');
  const peak=await page.evaluate(async()=>{const a=Sound.context.createAnalyser();a.fftSize=2048;Sound.master.connect(a);Sound.play('coin');await new Promise(r=>setTimeout(r,65));const s=new Float32Array(a.fftSize);a.getFloatTimeDomainData(s);Sound.master.disconnect(a);return Math.max(...s.map(Math.abs));});assert.ok(peak>.001);
  // Exercise the real exit → completion button → next-level flow. Capture both
  // openings at the same viewport/camera pose so layout changes are visible.
  await page.evaluate(()=>{game.resetPlayer();snapCamera();});
  await page.screenshot({path:'verification/level-01-opening.png'});
  const firstLayout=await page.evaluate(()=>game.world.platforms.map(p=>[p.x,p.y,p.w]));
  await page.evaluate(()=>{for(const c of game.world.coins)c.got=true;const pl=game.world.platforms.at(-1);Object.assign(game.player,{x:game.world.exit.x,y:pl.y-32,vy:0,grounded:true,platform:pl.id});game.step();});
  await page.getByRole('button',{name:'↑ KEYINGI DARAJA',exact:true}).click();await page.waitForFunction(()=>game.level===2&&game.state==='playing');
  assert.notDeepEqual(await page.evaluate(()=>game.world.platforms.map(p=>[p.x,p.y,p.w])),firstLayout);
  assert.equal(await page.locator('#levelValue').innerText(),'02/100');
  await page.screenshot({path:'verification/level-02-opening.png'});
  await page.reload();await page.getByRole('button',{name:'▶ DAVOM ETISH',exact:true}).click();await page.waitForFunction(()=>game.state==='playing');assert.equal(await page.evaluate(()=>game.level),2);
  await page.evaluate(async()=>{game.progress.unlocked=7;await startGame(7);for(const c of game.world.coins)if(c.id<4)c.got=true;const p=game.world.platforms[4];Object.assign(game.player,{x:p.x+p.w/2-12,y:p.y-32,vy:0,grounded:true});game.step();pauseGame();});
  assert.equal(await page.evaluate(()=>game.run.checkpoint),4);await page.reload();await page.getByRole('button',{name:'▶ DAVOM ETISH',exact:true}).click();await page.waitForFunction(()=>game.state==='playing');assert.equal(await page.evaluate(()=>game.level),7);assert.equal(await page.evaluate(()=>game.run.checkpoint),4);
  await page.evaluate(()=>{game.progress.wallet=20;for(let i=0;i<5;i++){game.die();for(let j=0;j<39;j++)game.step();if(game.state==='gameover'&&game.buyLife())showPlaying();}snapCamera();});assert.equal(await page.evaluate(()=>game.level),7);assert.equal(await page.evaluate(()=>game.run.deaths),5);await page.screenshot({path:'verification/desktop-game.png'});
  await page.locator('#mapBtn').click();assert.equal(await page.locator('.level-node').count(),100);assert.equal(await page.locator('[data-level="100"]').isDisabled(),true);await page.screenshot({path:'verification/stair-map.png'});await page.locator('#mapScroll').evaluate(el=>el.scrollTop=0);assert.ok(await page.locator('[data-level="100"]').isVisible());await page.locator('#closeMap').click();await page.getByRole('button',{name:'▶ DAVOM ETISH',exact:true}).click();await page.locator('#soundBtn').click();assert.equal(await page.evaluate(()=>Sound.muted),true);await page.reload();assert.equal(await page.evaluate(()=>Sound.muted),true);
  const phone=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:1});watch(phone);await phone.goto(url);await full(phone);await phone.screenshot({path:'verification/phone-portrait-menu.png'});await phone.getByRole('button',{name:'▶ BOSHLASH',exact:true}).tap();await phone.waitForFunction(()=>game.state==='playing');await phone.screenshot({path:'verification/phone-portrait-game.png'});
  const right=await phone.locator('#bR').boundingBox(),jump=await phone.locator('#bJ').boundingBox(),client=await phone.context().newCDPSession(phone);const p1={x:right.x+right.width/2,y:right.y+right.height/2,id:1},p2={x:jump.x+jump.width/2,y:jump.y+jump.height/2,id:2};const start=await phone.evaluate(()=>game.player.x);
  await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p1]});await phone.waitForTimeout(100);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p1,p2]});await phone.waitForTimeout(100);assert.ok(await phone.evaluate(x=>game.player.x>x+20&&game.player.y<-45,start));await client.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await phone.waitForFunction(()=>pointers.size===0,null,{timeout:2000});assert.equal(await phone.evaluate(()=>pointers.size),0);assert.equal(await phone.evaluate(()=>game.input.right),false);
  await phone.setViewportSize({width:844,height:390});await full(phone);await phone.screenshot({path:'verification/phone-landscape-game.png'});await phone.evaluate(()=>showHome());await phone.screenshot({path:'verification/phone-landscape-menu.png'});
  for(const viewport of [{width:360,height:640},{width:320,height:568}]){await phone.setViewportSize(viewport);await full(phone);const panel=await phone.locator('#panel').boundingBox();assert.ok(panel.y>=0&&panel.y+panel.height<=viewport.height+1,'menu cropped at '+JSON.stringify(viewport));}
  const localized=await browser.newPage({viewport:{width:320,height:568},isMobile:true,hasTouch:true});watch(localized);await localized.goto(url);await localized.locator('#languageMenuBtn').waitFor();
  const languages=await localized.evaluate(()=>I18n.locales);assert.equal(languages.length,18);
  async function menuFits(p){const result=await p.evaluate(()=>{const el=document.querySelector('#panel'),r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,innerWidth,innerHeight,contentWidth:el.scrollWidth,boxWidth:el.clientWidth};});assert.ok(result.x>=0&&result.y>=0&&result.x+result.width<=result.innerWidth+1&&result.y+result.height<=result.innerHeight+1,JSON.stringify(result));assert.ok(result.contentWidth<=result.boxWidth+2,'horizontal menu overflow '+JSON.stringify(result));}
  for(const language of languages){
   await localized.setViewportSize({width:320,height:568});await localized.locator('#languageMenuBtn').click();assert.equal(await localized.locator('[data-locale]').count(),18);await localized.locator('[data-locale="'+language.code+'"]').click();
   assert.equal(await localized.locator('html').getAttribute('lang'),language.code);assert.equal(await localized.locator('html').getAttribute('dir'),language.rtl?'rtl':'ltr');assert.ok((await localized.locator('#startBtn').innerText()).includes(await localized.evaluate(()=>T('start'))));await menuFits(localized);await full(localized);
   await localized.setViewportSize({width:844,height:390});await menuFits(localized);await full(localized);
   if(['ru','ar','ko'].includes(language.code)){await localized.setViewportSize({width:393,height:852});await localized.screenshot({path:'verification/menu-'+language.code+'.png'});}
  }
  await localized.setViewportSize({width:393,height:852});await localized.locator('#languageMenuBtn').click();await localized.screenshot({path:'verification/language-menu.png'});await localized.locator('[data-locale="ar"]').click();await localized.locator('#startBtn').click();await localized.waitForFunction(()=>game.state==='playing');
  assert.ok((await localized.locator('#bL').boundingBox()).x<(await localized.locator('#bR').boundingBox()).x);await localized.screenshot({path:'verification/arabic-game.png'});
  await localized.locator('#pauseBtn').click();await localized.locator('#pauseActions').getByRole('button',{name:await localized.evaluate(()=>T('language')),exact:true}).click();await localized.locator('[data-locale="en"]').click();assert.equal(await localized.evaluate(()=>game.state),'paused');await localized.locator('#resumeBtn').click();
  await localized.evaluate(async()=>{game.progress.unlocked=7;await startGame(7);for(const c of game.world.coins)if(c.id<4)c.got=true;const p=game.world.platforms[4];Object.assign(game.player,{x:p.x+p.w/2-12,y:p.y-32,vy:0,grounded:true});game.step();game.progress.wallet=7;for(let i=0;i<3;i++){game.die();for(let j=0;j<39;j++)game.step();}});
  assert.equal(await localized.evaluate(()=>game.state),'gameover');assert.equal(await localized.locator('#lifeValue .alive').count(),0);assert.equal(await localized.locator('#buyLifeBtn').isDisabled(),false);await menuFits(localized);await localized.screenshot({path:'verification/buy-life.png'});
  await localized.locator('#buyLifeBtn').tap();await localized.waitForFunction(()=>game.state==='playing');assert.deepEqual(await localized.evaluate(()=>[game.progress.lives,game.progress.wallet,game.run.checkpoint,game.world.coins.filter(c=>c.got).length]),[1,2,4,3]);
  await localized.reload();assert.equal(await localized.locator('html').getAttribute('lang'),'en');await localized.locator('#startBtn').click();await localized.waitForFunction(()=>game.state==='playing');assert.deepEqual(await localized.evaluate(()=>[game.level,game.progress.lives,game.progress.wallet,game.run.checkpoint]),[7,1,2,4]);
  await localized.evaluate(()=>{game.die();for(let j=0;j<39;j++)game.step();});assert.equal(await localized.locator('#buyLifeBtn').isDisabled(),true);await localized.locator('#lifeHomeBtn').click();await localized.locator('#startBtn').click();await localized.locator('#retryLevelBtn').waitFor();assert.equal(await localized.evaluate(()=>game.progress.lives),0);
  await localized.locator('#retryLevelBtn').click();await localized.waitForFunction(()=>game.state==='playing');assert.deepEqual(await localized.evaluate(()=>[game.level,game.progress.unlocked,game.progress.lives,game.progress.wallet,game.run.checkpoint,game.world.coins.filter(c=>c.got).length]),[7,7,3,2,0,0]);
  const shop=await require('./shop-browser.cjs')(browser,url,watch,menuFits);
  const upgrade=await require('./upgrade-browser.cjs')(browser,url,watch,menuFits);
  const premium=await require('./premium-browser.cjs')(browser,url,watch,menuFits);
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);fs.writeFileSync('verification/browser-tests.json',JSON.stringify({passed:true,shop,upgrade,premium,languages:18,arabicRTL:true,localeReload:true,lifePurchaseAndPersistence:true,insufficientFundsAndRetry:true,nextLevelLoadsDifferentLayout:true,levelTwoSurvivesReload:true,audioPeak:peak,fullScreenPortraitAndLandscape:true,multitouch:true,progressReload:true,checkpointAfterFiveDeaths:true,mapLevels:100,networkRequests:requests,pageErrors:errors},null,2));console.log('18 languages, RTL, lives, wallet purchases, reload, retry, levels, mobile controls and audio passed.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
