'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const errors=[],requests=[];fs.mkdirSync('verification',{recursive:true});
 try{
  const p=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
  await p.addInitScript(()=>{if(!localStorage.getItem('hellrun-hardcore-v2'))localStorage.setItem('hellrun-hardcore-v2',JSON.stringify({version:4,wallet:17,currentLevel:3,unlocked:3}));});
  await p.goto(pathToFileURL(path.resolve('build/game.html')).href);
  assert.equal(await p.title(),'HellRun MOD');assert.deepEqual(await p.evaluate(()=>[Build.channel,game.testMod,game.progress.unlocked,game.progress.wallet,game.progress.lives,SAVE_KEY]),['test-mod',true,100,1000000000,3,'hellrun-test-mod-v1']);
  assert.ok((await p.locator('.resources').innerText()).includes('∞'));assert.equal(await p.locator('#coinStoreBtn').count(),0);await p.screenshot({path:'verification/mod-phone-menu.png'});
  await p.locator('#homeMapBtn').tap();assert.equal(await p.locator('.level-node:not(:disabled)').count(),100);await p.locator('#mapScroll').evaluate(el=>el.scrollTop=0);await p.screenshot({path:'verification/mod-levels-open.png'});await p.locator('[data-level="100"]').tap();await p.waitForFunction(()=>game.level===100&&game.state==='playing');assert.equal(await p.locator('#walletValue').innerText(),'∞');
  await p.locator('#pauseBtn').tap();await p.locator('#pauseShopBtn').tap();await p.locator('#skinActionBtn').tap();await p.locator('#cancelSkinBtn').tap();assert.equal(await p.evaluate(()=>game.progress.ownedSkins.length),1);await p.locator('#skinActionBtn').tap();await p.locator('#confirmSkinBtn').tap();assert.deepEqual(await p.evaluate(()=>[game.progress.wallet,game.progress.equippedSkin]),[1000000000,'sunforged']);await p.locator('[data-pose="dash"]').tap();await p.screenshot({path:'verification/mod-ssplus-shop.png'});
  await p.locator('#shopBackBtn').tap();await p.locator('#resumeBtn').tap();await p.waitForFunction(()=>game.state==='playing');
  await p.evaluate(()=>{for(const c of game.world.coins)if(c.id<4)c.got=true;const pl=game.world.platforms[4];Object.assign(game.player,{x:pl.x+pl.w/2-12,y:pl.y-32,vx:0,vy:0,grounded:true,platform:pl.id,inv:20});game.step();for(let n=0;n<3;n++){game.die();for(let t=0;t<40;t++)game.step();}});
  assert.equal(await p.evaluate(()=>game.state),'gameover');assert.equal(await p.evaluate(()=>game.run.checkpoint),4);await p.locator('#buyLifeBtn').tap();await p.waitForFunction(()=>game.state==='playing');assert.deepEqual(await p.evaluate(()=>[game.progress.wallet,game.progress.lives,game.run.checkpoint]),[1000000000,1,4]);
  await p.reload();assert.deepEqual(await p.evaluate(()=>[game.level,game.progress.wallet,game.progress.unlocked,game.progress.equippedSkin,game.run.checkpoint,game.progress.lives]),[100,1000000000,100,'sunforged',4,1]);assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('hellrun-hardcore-v2'))),{version:4,wallet:17,currentLevel:3,unlocked:3});
  for(const code of ['uz','ar','ru','ko'])for(const size of [{width:320,height:568},{width:844,height:390}]){await p.setViewportSize(size);await p.evaluate(code=>{I18n.set(code);applyLocale();showHome();},code);const box=await p.locator('#panel').boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=size.width+1&&box.y+box.height<=size.height+1);assert.ok((await p.locator('.resources').innerText()).includes('∞'));}
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);fs.writeFileSync('verification/mod-browser.json',JSON.stringify({passed:true,all100LevelsSelectable:true,level100Played:true,infiniteWallet:true,skinPurchaseAndCancel:true,reviveWithoutDebit:true,checkpointReload:true,separateSave:true,phoneAndLandscape:true,errors,requests},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
